import type { Metadata } from "next";
import { Inter } from "next/font/google";
// Styles.
import "./styles/globals.css";
import "./features/features.css";
import "./components/AnimatedGrid/styles.css";
import { Header } from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  min-w-screen h-screen`}>
        <div className=" header flex justify-start px-[7rem] py-[1rem] m-0">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
