// Libraries.
import type { Metadata } from "next";
// Fonts.
import { Inter } from "next/font/google";
// Components.
import { Header } from "./components/Header/Header";
// Styles.
import "./styles/globals.css";
import "./features/styles-features.css";
import "./components/AnimatedGrid/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  min-w-screen h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
